#### IMPORT SECTION

In [5]:

import time
import webbrowser
from datetime import datetime, timedelta

# Import the required module from the fyers_apiv3 package
from fyers_apiv3 import fyersModel

# Configuration

#### Create Auth Token. Replace Client and Secret Key If Account Changed

In [6]:
def generate_fyers_access_token(
        client_id: str,
        secret_key: str,
        redirect_uri: str,
        state: str = "sample_state"
) -> dict:
    """
    Handles FYERS OAuth flow and returns access token response.

    Returns
    -------
    dict
        Full response containing access_token, refresh_token, expiry, etc.
    """

    # -------------------------------
    # Step 1: Generate auth URL
    # -------------------------------
    session = fyersModel.SessionModel(
        client_id=client_id,
        secret_key=secret_key,
        redirect_uri=redirect_uri,
        response_type="code",
        state=state
    )

    auth_url = session.generate_authcode()
    webbrowser.open(auth_url)

    # -------------------------------
    # Step 2: User pastes redirected URL
    # -------------------------------
    raw_code = input("Paste redirected URL here: ").strip()

    try:
        auth_code = raw_code.split("auth_code=")[1].split("&")[0]
    except IndexError:
        raise ValueError("Invalid redirect URL. Auth code not found.")

    # -------------------------------
    # Step 3: Exchange auth_code for access_token
    # -------------------------------
    session = fyersModel.SessionModel(
        client_id=client_id,
        secret_key=secret_key,
        redirect_uri=redirect_uri,
        response_type="code",
        grant_type="authorization_code"
    )

    session.set_token(auth_code)
    token_response = session.generate_token()

    return token_response

In [7]:
# client_id="ALT6RUE1IF-100"
# secret_key="0UT0LW5PE4"
client_id = "CMNM5XUOHX-100"  ## Client_id here refers to APP_ID of the created app
secret_key = "VVXICRVEQM"  ## app_secret key which you got after creating the app
# redirect_uri="https://luvratan.tech/"
redirect_uri = "http://localhost.com/"  ## redircet_uri you entered while creating APP.
token_response = generate_fyers_access_token(
    client_id=client_id,
    secret_key=secret_key,
    redirect_uri=redirect_uri
)

access_token = token_response["access_token"]
print("Access Token:", access_token)

Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIl0sImF0X2hhc2giOiJnQUFBQUFCcDdMWTNQWnJsdnlBYVVIdjVYX2I3cHpISjBLQXJUcmdsYlRLTnBkbTVaS2ktZ2JIZzI3Sl9KcldaS2pBNjc2VjN2Q0hHWkEwZVFoQVRjWllyODJ1TWlGaWxGcXBvU09URGhDVFJ6aXVfQk90UDctVT0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI5MGM4MWZiZDAzM2IzNzUyOThiYTJhMmM4NGFmZmFkNzVhZmRjMzdmNGJhZTNiY2UyMjc4MjRkZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiRkFJMjE4OTEiLCJhcHBUeXBlIjoxMDAsImV4cCI6MTc3NzE2MzQwMCwiaWF0IjoxNzc3MTIwODIzLCJpc3MiOiJhcGkuZnllcnMuaW4iLCJuYmYiOjE3NzcxMjA4MjMsInN1YiI6ImFjY2Vzc190b2tlbiJ9.ITTE6zx3gX4xfxx3JjrY_8foVS_BczAJZ4Ze-jw95O8

#### Add Ticker and Its Configuration. Resolution=5

In [8]:
ticker = "NSE:ADANIPORTS-EQ"
start_date = datetime(2024, 1, 1)
start_date_formatted = start_date.strftime("%Y-%m-%d")
# end_date = datetime(2026, 1, 9).strftime("%Y-%m-%d")
end_date = datetime.now()
end_date_formatted = datetime.now().strftime("%Y-%m-%d")
resolution = 5

Resolution=15

In [9]:
fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")
resolution = 15
data = {
    "symbol": ticker,
    "resolution": resolution,
    "date_format": "1",
    "range_from": start_date_formatted,
    "range_to": (start_date + timedelta(days=100)).strftime("%Y-%m-%d"),
    "cont_flag": "1"
}

response = fyers.history(data=data)
print(response)

{'candles': [[1704080700, 1026.55, 1028.9, 1025.0, 1026.15, 156982], [1704081600, 1026.0, 1027.05, 1024.1, 1024.5, 59143], [1704082500, 1024.6, 1026.35, 1023.0, 1025.0, 57906], [1704083400, 1025.0, 1025.25, 1023.1, 1023.6, 31236], [1704084300, 1023.6, 1025.8, 1023.1, 1025.0, 34453], [1704085200, 1025.0, 1044.65, 1024.75, 1042.9, 362307], [1704086100, 1042.6, 1045.9, 1040.1, 1042.0, 291578], [1704087000, 1042.0, 1042.75, 1036.0, 1039.8, 125636], [1704087900, 1039.8, 1041.15, 1037.3, 1040.8, 61735], [1704088800, 1040.8, 1041.3, 1039.1, 1040.8, 54303], [1704089700, 1040.8, 1050.85, 1040.5, 1047.6, 428813], [1704090600, 1047.05, 1049.45, 1043.8, 1048.45, 148117], [1704091500, 1048.0, 1048.7, 1046.1, 1046.4, 74298], [1704092400, 1046.4, 1057.45, 1045.5, 1053.95, 454113], [1704093300, 1053.65, 1056.4, 1052.1, 1054.5, 165732], [1704094200, 1054.5, 1055.7, 1051.55, 1053.05, 118908], [1704095100, 1053.05, 1056.5, 1050.6, 1055.7, 120947], [1704096000, 1055.7, 1056.6, 1053.0, 1055.0, 151557], [1704096900, 1055.0, 1057.95, 1054.6, 1056.25, 117675], [1704097800, 1056.25, 1057.15, 1055.5, 1055.95, 72441], [1704098700, 1055.85, 1056.3, 1051.6, 1052.2, 105995], [1704099600, 1052.2, 1055.2, 1052.2, 1054.05, 89074], [1704100500, 1054.05, 1055.5, 1053.3, 1054.75, 87254], [1704101400, 1054.75, 1056.0, 1045.2, 1045.5, 343990], [1704102300, 1045.5, 1047.95, 1039.6, 1041.1, 274238], [1704167100, 1047.85, 1048.5, 1039.2, 1043.5, 246863], [1704168000, 1043.5, 1051.0, 1039.5, 1049.8, 200892], [1704168900, 1049.8, 1049.8, 1039.05, 1040.05, 228692], [1704169800, 1040.4, 1046.1, 1036.4, 1043.1, 152082], [1704170700, 1043.1, 1043.75, 1035.8, 1037.85, 167086], [1704171600, 1037.85, 1041.05, 1031.1, 1035.7, 161082], [1704172500, 1035.4, 1040.95, 1034.7, 1040.9, 183754], [1704173400, 1040.9, 1046.6, 1039.4, 1043.0, 117087], [1704174300, 1043.0, 1056.8, 1042.25, 1054.1, 292283], [1704175200, 1054.1, 1056.15, 1050.35, 1055.2, 209885], [1704176100, 1055.4, 1057.8, 1053.05, 1054.45, 157758], [1704177000, 1054.15, 1070.0, 1051.5, 1067.5, 445979], [1704177900, 1067.5, 1068.75, 1060.05, 1060.4, 274150], [1704178800, 1060.4, 1062.95, 1060.0, 1060.2, 120430], [1704179700, 1060.2, 1061.35, 1057.05, 1057.15, 86207], [1704180600, 1057.15, 1058.95, 1054.6, 1055.55, 83615], [1704181500, 1055.55, 1058.75, 1054.7, 1056.8, 67941], [1704182400, 1056.8, 1059.6, 1056.55, 1058.0, 60792], [1704183300, 1058.0, 1061.5, 1056.5, 1060.85, 67750], [1704184200, 1060.75, 1065.25, 1060.45, 1062.9, 160352], [1704185100, 1062.95, 1069.2, 1061.0, 1065.7, 346816], [1704186000, 1065.95, 1076.6, 1065.0, 1075.45, 706225], [1704186900, 1075.45, 1082.9, 1074.0, 1077.05, 745933], [1704187800, 1077.05, 1081.4, 1073.7, 1077.3, 572111], [1704188700, 1077.1, 1080.5, 1076.7, 1078.55, 486685], [1704253500, 1105.0, 1116.45, 1091.7, 1105.75, 4356207], [1704254400, 1106.6, 1125.0, 1105.6, 1120.1, 2582510], [1704255300, 1120.0, 1140.85, 1119.55, 1136.6, 2772768], [1704256200, 1136.15, 1139.3, 1125.15, 1133.65, 1759018], [1704257100, 1134.1, 1134.6, 1111.0, 1125.0, 1817710], [1704258000, 1125.0, 1144.0, 1062.75, 1090.0, 5098103], [1704258900, 1089.55, 1117.0, 1076.4, 1099.25, 3139296], [1704259800, 1099.15, 1102.1, 1083.8, 1090.95, 1496378], [1704260700, 1090.95, 1098.5, 1086.6, 1086.7, 821683], [1704261600, 1086.75, 1088.0, 1078.55, 1084.0, 1009313], [1704262500, 1084.4, 1088.3, 1072.65, 1083.65, 794991], [1704263400, 1083.5, 1090.0, 1080.3, 1088.5, 621839], [1704264300, 1088.5, 1095.0, 1084.0, 1090.05, 548946], [1704265200, 1090.55, 1094.85, 1088.6, 1094.6, 362469], [1704266100, 1094.6, 1094.6, 1088.0, 1092.3, 254042], [1704267000, 1092.3, 1093.95, 1089.0, 1092.9, 281839], [1704267900, 1092.9, 1101.55, 1091.45, 1098.0, 674836], [1704268800, 1098.0, 1103.0, 1096.5, 1099.25, 466704], [1704269700, 1099.7, 1106.95, 1097.0, 1103.95, 528259], [1704270600, 1103.95, 1108.8, 1100.85, 1106.65, 531342], [1704271500, 1106.15, 1107.45, 1097.0, 1105.4, 649752], [1704272400, 1104.8, 1109.0, 1100.25, 1102.65, 514971], [1704273300, 1102.4, 1104.75, 1097.1, 1098.2, 398079], [1704274200, 1097.55, 1100.9, 1093.15, 1094.1, 739294], [1704275100, 1095.0, 1095.7, 1090.0, 1094.7, 834073], [1704339900, 1117.0, 1118.75, 1107.0, 1111.7, 2006855], [1704340800, 1111.6, 1112.65, 1103.55, 1109.25, 643015], [1704341700, 1109.25, 1114.6, 1108.05, 1112.0, 387867], [1704342600, 1112.0, 1117.95, 1111.45, 1117.0, 424811], [1704343500, 1117.0, 1118.3, 1112.05, 1113.95, 409929], [1704344400, 1113.55, 1114.7, 1109.4, 1113.75, 306039], [1704345300, 1113.95, 1114.0, 1108.55, 1110.0, 244404], [1704346200, 1110.0, 1113.6, 1109.65, 1112.05, 163253], [1704347100, 1112.05, 1114.95, 1110.0, 1111.65, 189317], [1704348000, 1112.0, 1116.0, 1111.05, 1114.55, 211444], [1704348900, 1114.3, 1114.8, 1111.05, 1114.6, 131186], [1704349800, 1114.6, 1117.0, 1113.35, 1115.95, 220591], [1704350700, 1115.95, 1122.05, 1115.0, 1119.4, 432818], [1704351600, 1119.4, 1121.4, 1118.0, 1119.5, 310336], [1704352500, 1119.5, 1122.0, 1115.9, 1116.5, 291205], [1704353400, 1116.5, 1119.7, 1116.45, 1116.7, 138659], [1704354300, 1116.65, 1117.95, 1115.0, 1116.6, 168877], [1704355200, 1116.6, 1118.7, 1116.05, 1118.65, 116462], [1704356100, 1118.5, 1121.7, 1117.9, 1121.5, 218069], [1704357000, 1121.5, 1131.0, 1121.35, 1125.9, 792961], [1704357900, 1125.9, 1127.5, 1121.3, 1123.8, 333105], [1704358800, 1123.95, 1127.95, 1123.5, 1126.65, 275721], [1704359700, 1126.65, 1127.0, 1124.2, 1125.55, 198052], [1704360600, 1125.1, 1125.95, 1122.05, 1123.6, 522028], [1704361500, 1123.3, 1124.5, 1120.55, 1122.0, 630709], [1704426300, 1129.1, 1141.0, 1125.4, 1137.25, 1129758], [1704427200, 1137.25, 1138.2, 1129.25, 1133.6, 888964], [1704428100, 1134.15, 1150.0, 1132.45, 1148.5, 869893], [1704429000, 1148.5, 1154.7, 1143.0, 1144.7, 789137], [1704429900, 1144.75, 1148.55, 1143.0, 1144.4, 265235], [1704430800, 1144.6, 1153.8, 1143.2, 1146.55, 421368], [1704431700, 1146.05, 1147.6, 1137.9, 1145.85, 543739], [1704432600, 1145.85, 1152.5, 1143.95, 1150.95, 363348], [1704433500, 1150.95, 1154.45, 1146.05, 1152.1, 322680], [1704434400, 1152.1, 1159.7, 1151.2, 1155.35, 648888], [1704435300, 1155.25, 1158.5, 1152.65, 1155.55, 261815], [1704436200, 1155.85, 1158.0, 1153.3, 1155.9, 173299], [1704437100, 1155.9, 1160.0, 1155.8, 1157.8, 234631], [1704438000, 1157.8, 1159.9, 1156.6, 1157.0, 182836], [1704438900, 1156.8, 1157.5, 1153.55, 1154.7, 185372], [1704439800, 1154.75, 1157.5, 1151.65, 1154.6, 171477], [1704440700, 1154.6, 1158.25, 1153.65, 1155.8, 171795], [1704441600, 1155.8, 1156.5, 1150.0, 1153.25, 224526], [1704442500, 1153.0, 1156.25, 1151.85, 1155.5, 187508], [1704443400, 1155.4, 1155.5, 1143.85, 1146.0, 409547], [1704444300, 1146.5, 1149.7, 1138.0, 1141.0, 566288], [1704445200, 1141.0, 1149.0, 1140.05, 1148.8, 357465], [1704446100, 1149.0, 1154.7, 1148.8, 1153.95, 335051], [1704447000, 1153.45, 1156.0, 1152.4, 1154.95, 410254], [1704447900, 1154.95, 1155.55, 1152.0, 1153.0, 503791], [1704685500, 1160.0, 1169.25, 1155.25, 1156.8, 1339377], [1704686400, 1157.2, 1162.6, 1153.0, 1159.6, 525511], [1704687300, 1159.6, 1162.0, 1152.0, 1159.3, 281377], [1704688200, 1159.3, 1166.0, 1157.1, 1164.25, 227338], [1704689100, 1164.35, 1172.0, 1161.0, 1167.65, 687230], [1704690000, 1168.35, 1169.5, 1162.5, 1163.7, 194934], [1704690900, 1163.7, 1167.45, 1163.65, 1166.85, 136937], [1704691800, 1167.3, 1171.7, 1166.0, 1168.55, 277605], [1704692700, 1168.7, 1176.9, 1168.1, 1174.5, 489154], [1704693600, 1174.65, 1180.0, 1174.45, 1179.85, 376087], [1704694500, 1179.75, 1181.9, 1173.5, 1174.15, 409912], [1704695400, 1174.3, 1182.0, 1173.95, 1179.95, 450075], [1704696300, 1179.95, 1179.95, 1172.4, 1172.5, 230884], [1704697200, 1172.55, 1174.0, 1171.0, 1171.5, 203943], [1704698100, 1171.5, 1176.6, 1169.8, 1175.75, 209904], [1704699000, 1175.7, 1179.7, 1175.1, 1178.7, 197441], [1704699900, 1178.7, 1181.0, 1177.3, 1179.9, 206377], [1704700800, 1179.65, 1181.0, 1177.35, 1178.35, 173274], [1704701700, 1178.55, 1178.8, 1175.3, 1177.9, 167215], [1704702600, 1178.1, 1178.5, 1173.65, 1175.5, 173803], [1704703500, 1175.5, 1176.1, 1170.75, 1170.75, 252998], [1704704400, 1170.7, 1172.3, 1166.3, 1170.0, 386909], [1704705300, 1169.75, 1174.2, 1168.05, 1168.8, 323409], [1704706200, 1169.05, 1170.65, 1166.05, 1166.3, 332327], [1704707100, 1166.7, 1174.95, 1165.0, 1172.4, 504236], [1704771900, 1182.0, 1198.5, 1178.5, 1194.6, 1279733], [1704772800, 1194.6, 1202.5, 1194.0, 1198.9, 1350116], [1704773700, 1199.0, 1213.25, 1198.4, 1209.0, 1722545], [1704774600, 1209.0, 1224.9, 1208.15, 1223.5, 1580779], [1704775500, 1223.75, 1228.0, 1220.7, 1224.9, 788796], [1704776400, 1224.9, 1229.9, 1223.4, 1225.5, 594595], [1704777300, 1225.9, 1226.0, 1214.05, 1215.2, 733522], [1704778200, 1214.5, 1216.0, 1205.5, 1206.0, 619900], [1704779100, 1206.45, 1208.95, 1201.5, 1202.2, 542980], [1704780000, 1202.2, 1207.0, 1198.5, 1204.0, 726599], [1704780900, 1204.0, 1207.0, 1199.4, 1201.5, 335128], [1704781800, 1201.75, 1201.9, 1191.55, 1195.45, 560108], [1704782700, 1195.1, 1195.95, 1190.1, 1195.25, 327840], [1704783600, 1195.2, 1199.25, 1191.25, 1192.15, 305523], [1704784500, 1192.0, 1194.7, 1190.1, 1194.0, 213212], [1704785400, 1194.0, 1194.0, 1190.35, 1192.5, 181907], [1704786300, 1192.8, 1197.5, 1192.4, 1197.1, 171034], [1704787200, 1197.0, 1202.5, 1195.1, 1201.0, 243244], [1704788100, 1201.0, 1205.55, 1200.55, 1204.55, 309530], [1704789000, 1204.85, 1207.35, 1203.4, 1205.2, 274604], [1704789900, 1205.7, 1206.45, 1192.8, 1194.55, 377728], [1704790800, 1194.55, 1202.1, 1193.65, 1195.8, 322798], [1704791700, 1195.8, 1201.55, 1195.8, 1199.75, 212845], [1704792600, 1199.8, 1200.9, 1194.0, 1195.35, 376562], [1704793500, 1195.55, 1202.0, 1192.2, 1200.95, 547639], [1704858300, 1220.0, 1220.0, 1198.75, 1200.4, 1446986], [1704859200, 1200.1, 1212.0, 1197.0, 1210.45, 660674], [1704860100, 1210.55, 1212.0, 1202.0, 1204.5, 482429], [1704861000, 1205.1, 1208.7, 1200.5, 1205.35, 357040], [1704861900, 1205.35, 1206.95, 1202.15, 1204.0, 201669], [1704862800, 1204.55, 1208.5, 1203.45, 1204.5, 153622], [1704863700, 1204.5, 1207.25, 1203.45, 1206.65, 102449], [1704864600, 1206.9, 1207.0, 1203.5, 1206.0, 120530], [1704865500, 1206.0, 1206.5, 1204.15, 1205.5, 101435], [1704866400, 1205.5, 1211.0, 1203.05, 1210.0, 221924], [1704867300, 1209.75, 1214.8, 1208.2, 1211.8, 407754], [1704868200, 1211.8, 1214.0, 1207.5, 1209.85, 286117], [1704869100, 1209.85, 1211.7, 1207.55, 1210.1, 145420], [1704870000, 1210.1, 1212.9, 1209.2, 1209.85, 180895], [1704870900, 1209.85, 1214.0, 1206.35, 1210.8, 320330], [1704871800, 1211.25, 1213.5, 1210.5, 1211.45, 139712], [1704872700, 1211.45, 1213.0, 1210.2, 1211.85, 88641], [1704873600, 1211.85, 1212.5, 1209.1, 1210.55, 141878], [1704874500, 1210.55, 1211.0, 1208.25, 1209.85, 132771], [1704875400, 1209.85, 1212.0, 1209.1, 1212.0, 84245], [1704876300, 1212.0, 1215.0, 1210.75, 1211.45, 235729], [1704877200, 1211.45, 1215.95, 1211.45, 1215.15, 213062], [1704878100, 1215.15, 1216.85, 1212.8, 1212.8, 201502], [1704879000, 1212.8, 1214.5, 1211.0, 1213.35, 245953], [1704879900, 1213.45, 1216.5, 1213.35, 1215.0, 363397], [1704944700, 1221.0, 1223.6, 1212.8, 1217.0, 719471], [1704945600, 1217.0, 1217.6, 1208.5, 1210.3, 385242], [1704946500, 1210.5, 1214.0, 1207.35, 1209.4, 245218], [1704947400, 1209.0, 1210.95, 1205.5, 1207.2, 189977], [1704948300, 1207.2, 1208.8, 1204.0, 1207.0, 165048], [1704949200, 1207.0, 1208.4, 1204.5, 1205.55, 103709], [1704950100, 1205.55, 1207.0, 1203.05, 1206.9, 110631], [1704951000, 1206.7, 1209.65, 1206.0, 1208.7, 79926], [1704951900, 1208.7, 1211.8, 1208.6, 1209.85, 99833], [1704952800, 1209.85, 1210.9, 1207.4, 1208.4, 58976], [1704953700, 1208.4, 1208.95, 1206.0, 1206.75, 55601], [1704954600, 1206.75, 1207.5, 1206.05, 1207.1, 41636], [1704955500, 1207.1, 1211.5, 1205.1, 1209.55, 113334], [1704956400, 1209.55, 1210.0, 1208.4, 1209.5, 57619], [1704957300, 1209.65, 1210.0, 1207.45, 1208.35, 49891], [1704958200, 1207.75, 1209.45, 1207.35, 1209.05, 43924], [1704959100, 1209.05, 1209.1, 1207.0, 1207.5, 46857], [1704960000, 1207.95, 1207.95, 1205.1, 1206.4, 82469], [1704960900, 1206.4, 1208.0, 1205.1, 1207.8, 71774], [1704961800, 1207.8, 1207.95, 1201.1, 1202.25, 159484], [1704962700, 1202.25, 1206.0, 1201.05, 1205.45, 123707], [1704963600, 1205.45, 1206.7, 1204.8, 1205.7, 92182], [1704964500, 1205.7, 1206.45, 1204.65, 1205.0, 66788], [1704965400, 1205.1, 1205.4, 1202.45, 1202.8, 181478], [1704966300, 1202.8, 1205.25, 1200.0, 1204.0, 375611], [1705031100, 1210.4, 1210.4, 1201.1, 1203.0, 416317], [1705032000, 1203.0, 1216.0, 1201.05, 1213.1, 362542], [1705032900, 1213.05, 1218.75, 1212.3, 1216.95, 334357], [1705033800, 1217.0, 1218.05, 1214.55, 1216.45, 188279], [1705034700, 1216.45, 1218.55, 1215.25, 1216.25, 113501], [1705035600, 1216.25, 1216.75, 1213.0, 1214.05, 86451], [1705036500, 1214.05, 1214.5, 1212.25, 1212.8, 52536], [1705037400, 1212.8, 1213.4, 1207.8, 1209.55, 146665], [1705038300, 1209.5, 1209.65, 1207.0, 1209.0, 73147], [1705039200, 1209.0, 1209.95, 1207.6, 1207.95, 88058], [1705040100, 1207.95, 1209.7, 1206.65, 1206.8, 104383], [1705041000, 1206.65, 1209.5, 1204.35, 1209.3, 121243], [1705041900, 1209.3, 1209.6, 1206.5, 1208.55, 63213], [1705042800, 1208.55, 1210.5, 1205.55, 1206.35, 105133], [1705043700, 1206.35, 1207.5, 1205.55, 1207.3, 64563], [1705044600, 1207.05, 1210.5, 1206.65, 1209.9, 84056], [1705045500, 1209.9, 1209.9, 1207.3, 1209.1, 118794], [1705046400, 1209.2, 1214.9, 1208.55, 1210.1, 211324], [1705047300, 1210.1, 1211.3, 1207.85, 1210.4, 129487], [1705048200, 1210.45, 1210.7, 1206.5, 1207.9, 137899], [1705049100, 1207.9, 1210.55, 1206.8, 1209.9, 170222], [1705050000, 1209.9, 1213.35, 1209.65, 1211.45, 215834], [1705050900, 1211.4, 1211.45, 1207.6, 1207.9, 131840], [1705051800, 1207.9, 1209.2, 1205.25, 1206.5, 158914], [1705052700, 1206.25, 1208.95, 1205.8, 1207.0, 231582], [1705290300, 1214.0, 1215.35, 1207.1, 1207.7, 306662], [1705291200, 1207.4, 1207.65, 1203.15, 1203.65, 201968], [1705292100, 1203.65, 1203.65, 1191.0, 1191.45, 221137], [1705293000, 1191.45, 1196.6, 1189.1, 1192.1, 196022], [1705293900, 1192.1, 1195.5, 1192.0, 1195.1, 77414], [1705294800, 1195.15, 1197.8, 1194.55, 1195.8, 83073], [1705295700, 1195.8, 1197.4, 1193.1, 1197.4, 78127], [1705296600, 1197.5, 1207.8, 1197.1, 1207.05, 230837], [1705297500, 1207.05, 1209.7, 1205.55, 1207.8, 172422], [1705298400, 1207.8, 1209.8, 1205.0, 1208.25, 95691], [1705299300, 1208.25, 1208.4, 1205.5, 1205.5, 43375], [1705300200, 1205.5, 1207.55, 1204.6, 1205.4, 50050], [1705301100, 1205.4, 1206.8, 1204.7, 1204.8, 56925], [1705302000, 1204.8, 1206.6, 1204.75, 1206.0, 44468], [1705302900, 1205.85, 1206.45, 1204.1, 1204.15, 35633], [1705303800, 1204.15, 1204.4, 1202.0, 1203.0, 89613], [1705304700, 1203.05, 1204.25, 1201.15, 1202.0, 49289], [1705305600, 1202.0, 1203.0, 1201.1, 1202.95, 48303], [1705306500, 1202.95, 1208.1, 1200.5, 1208.1, 94434], [1705307400, 1208.1, 1209.9, 1204.2, 1205.5, 111509], [1705308300, 1205.5, 1207.4, 1204.0, 1204.75, 61391], [1705309200, 1204.75, 1207.2, 1204.0, 1207.0, 59523], [1705310100, 1207.0, 1207.5, 1205.2, 1205.65, 68552], [1705311000, 1205.65, 1206.9, 1202.0, 1202.75, 121568], [1705311900, 1202.3, 1207.5, 1202.0, 1203.6, 226581], [1705376700, 1203.6, 1212.0, 1202.05, 1205.15, 390391], [1705377600, 1205.15, 1206.95, 1204.05, 1205.45, 151489], [1705378500, 1205.45, 1207.85, 1202.65, 1203.5, 106153], [1705379400, 1203.45, 1203.45, 1199.0, 1199.9, 223007], [1705380300, 1200.0, 1200.55, 1197.75, 1200.55, 173847], [1705381200, 1200.05, 1200.85, 1199.4, 1199.85, 69415], [1705382100, 1199.85, 1200.05, 1197.6, 1199.6, 97619], [1705383000, 1199.7, 1200.1, 1199.0, 1199.65, 42458], [1705383900, 1199.6, 1200.2, 1199.0, 1199.25, 88253], [1705384800, 1199.25, 1199.55, 1196.0, 1197.2, 107163], [1705385700, 1197.2, 1200.95, 1194.65, 1200.0, 145695], [1705386600, 1200.0, 1200.35, 1196.5, 1197.7, 82503], [1705387500, 1197.65, 1200.4, 1197.0, 1198.6, 66203], [1705388400, 1198.6, 1200.0, 1198.6, 1199.7, 48517], [1705389300, 1199.7, 1200.1, 1198.0, 1199.2, 54207], [1705390200, 1199.1, 1199.35, 1191.4, 1193.7, 184605], [1705391100, 1193.7, 1196.2, 1190.0, 1193.3, 166164], [1705392000, 1193.0, 1193.1, 1186.8, 1191.15, 184828], [1705392900, 1191.0, 1193.45, 1190.0, 1191.9, 77747], [1705393800, 1191.75, 1193.95, 1190.15, 1192.85, 86750], [1705394700, 1192.8, 1194.2, 1191.55, 1193.75, 101732], [1705395600, 1193.7, 1195.85, 1191.65, 1195.15, 98757], [1705396500, 1195.1, 1195.5, 1193.05, 1194.45, 85896], [1705397400, 1194.3, 1195.4, 1193.1, 1193.65, 130566], [1705398300, 1193.65, 1195.0, 1190.4, 1194.5, 209428], [1705463100, 1180.0, 1204.7, 1177.45, 1190.5, 747626], [1705464000, 1190.0, 1193.15, 1189.0, 1189.4, 227245], [1705464900, 1189.6, 1191.55, 1187.0, 1189.1, 175718], [1705465800, 1189.3, 1191.5, 1188.1, 1191.2, 55863], [1705466700, 1190.55, 1196.9, 1190.55, 1196.4, 144476], [1705467600, 1196.35, 1200.8, 1189.05, 1191.5, 171918], [1705468500, 1191.5, 1193.95, 1190.6, 1192.8, 61654], [1705469400, 1192.45, 1193.5, 1184.4, 1187.25, 549028], [1705470300, 1187.25, 1187.3, 1181.25, 1182.4, 270949], [1705471200, 1182.4, 1183.15, 1176.25, 1178.3, 342681], [1705472100, 1178.6, 1178.95, 1175.75, 1177.8, 98952], [1705473000, 1177.75, 1178.45, 1173.1, 1177.15, 174164], [1705473900, 1177.15, 1179.85, 1176.2, 1177.9, 100437], [1705474800, 1177.8, 1180.5, 1177.5, 1178.1, 89895], [1705475700, 1178.1, 1179.7, 1177.0, 1178.15, 69270], [1705476600, 1178.15, 1179.25, 1175.8, 1177.5, 85564], [1705477500, 1177.5, 1179.0, 1175.05, 1175.4, 68818], [1705478400, 1175.4, 1176.8, 1172.0, 1175.45, 85978], [1705479300, 1175.45, 1181.45, 1169.3, 1176.05, 120547], [1705480200, 1176.05, 1179.0, 1175.25, 1175.25, 121773], [1705481100, 1175.25, 1176.8, 1165.65, 1166.35, 128201], [1705482000, 1165.65, 1168.55, 1160.5, 1161.75, 347211], [1705482900, 1161.8, 1163.0, 1159.45, 1161.8, 385968], [1705483800, 1161.45, 1168.95, 1161.1, 1167.05, 291786], [1705484700, 1167.05, 1174.1, 1165.6, 1169.9, 352302], [1705549500, 1171.05, 1184.3, 1170.3, 1179.65, 653526], [1705550400, 1179.65, 1182.35, 1159.5, 1164.55, 732760], [1705551300, 1164.9, 1165.2, 1143.45, 1152.45, 1239312], [1705552200, 1152.45, 1165.75, 1151.35, 1164.5, 604930], [1705553100, 1164.5, 1165.95, 1155.5, 1156.25, 296575], [1705554000, 1156.25, 1158.75, 1151.9, 1155.0, 264935], [1705554900, 1155.0, 1158.65, 1153.65, 1155.75, 305551], [1705555800, 1155.75, 1156.0, 1150.6, 1154.75, 129201], [1705556700, 1155.0, 1155.5, 1152.65, 1154.95, 65537], [1705557600, 1154.95, 1157.05, 1149.0, 1152.05, 197098], [1705558500, 1152.05, 1157.35, 1151.4, 1156.5, 47191], [1705559400, 1156.5, 1157.5, 1152.1, 1154.55, 121478], [1705560300, 1154.55, 1156.95, 1153.05, 1153.55, 51011], [1705561200, 1153.55, 1155.75, 1144.1, 1144.75, 115634], [1705562100, 1144.75, 1149.45, 1144.3, 1148.25, 64531], [1705563000, 1148.3, 1150.85, 1147.5, 1149.2, 76033], [1705563900, 1149.2, 1152.3, 1148.8, 1151.55, 55621], [1705564800, 1151.55, 1152.0, 1148.65, 1150.3, 37626], [1705565700, 1150.4, 1153.4, 1149.5, 1152.45, 44827], [1705566600, 1152.95, 1155.5, 1151.5, 1154.5, 38149], [1705567500, 1154.5, 1155.15, 1151.8, 1153.0, 39592], [1705568400, 1153.25, 1155.85, 1151.6, 1155.35, 61964], [1705569300, 1155.5, 1157.1, 1153.0, 1155.1, 145206], [1705570200, 1155.0, 1156.0, 1153.2, 1154.2, 157779], [1705571100, 1154.25, 1159.2, 1152.2, 1155.0, 372151], [1705635900, 1162.25, 1166.8, 1159.6, 1163.55, 326496], [1705636800, 1163.15, 1164.3, 1155.5, 1156.5, 190734], [1705637700, 1156.6, 1160.45, 1155.0, 1159.4, 153605], [1705638600, 1159.45, 1159.55, 1154.2, 1157.55, 126747], [1705639500, 1157.55, 1162.45, 1157.55, 1160.85, 135292], [1705640400, 1160.85, 1162.2, 1158.6, 1161.15, 97171], [1705641300, 1161.15, 1161.7, 1158.75, 1158.95, 65611], [1705642200, 1158.95, 1160.0, 1155.0, 1156.8, 81864], [1705643100, 1156.8, 1156.8, 1153.0, 1154.9, 73908], [1705644000, 1154.9, 1155.6, 1151.0, 1153.5, 104915], [1705644900, 1153.5, 1157.8, 1153.0, 1155.55, 77447], [1705645800, 1155.55

#### Get Data

In [10]:
import pandas as pd


def fyers_history_to_df(response: dict) -> pd.DataFrame:
    """
    Convert FYERS history API response to a pandas DataFrame.
    Shifts intraday candle timestamps forward by 15 minutes.
    """

    if response.get("s") != "ok":
        raise ValueError(f"FYERS API error: {response}")
    print(response["candles"])
    df = pd.DataFrame(
        response["candles"],
        columns=["timestamp", "open", "high", "low", "close", "volume"]
    )

    # Convert UNIX epoch → timezone-aware datetime (IST)
    df["datetime"] = (
        pd.to_datetime(df["timestamp"], unit="s", utc=True)
        .dt.tz_convert("Asia/Kolkata")
    )

    # Shift candle time forward by 15 minutes
    df["datetime"] = df["datetime"] + pd.Timedelta(minutes=resolution)

    # Sort by adjusted time
    df = df.sort_values("datetime")

    # Drop raw timestamp if not needed
    df = df.drop(columns=["timestamp"])

    return df


df = fyers_history_to_df(response)
df

[[1704080700, 1026.55, 1028.9, 1025.0, 1026.15, 156982], [1704081600, 1026.0, 1027.05, 1024.1, 1024.5, 59143], [1704082500, 1024.6, 1026.35, 1023.0, 1025.0, 57906], [1704083400, 1025.0, 1025.25, 1023.1, 1023.6, 31236], [1704084300, 1023.6, 1025.8, 1023.1, 1025.0, 34453], [1704085200, 1025.0, 1044.65, 1024.75, 1042.9, 362307], [1704086100, 1042.6, 1045.9, 1040.1, 1042.0, 291578], [1704087000, 1042.0, 1042.75, 1036.0, 1039.8, 125636], [1704087900, 1039.8, 1041.15, 1037.3, 1040.8, 61735], [1704088800, 1040.8, 1041.3, 1039.1, 1040.8, 54303], [1704089700, 1040.8, 1050.85, 1040.5, 1047.6, 428813], [1704090600, 1047.05, 1049.45, 1043.8, 1048.45, 148117], [1704091500, 1048.0, 1048.7, 1046.1, 1046.4, 74298], [1704092400, 1046.4, 1057.45, 1045.5, 1053.95, 454113], [1704093300, 1053.65, 1056.4, 1052.1, 1054.5, 165732], [1704094200, 1054.5, 1055.7, 1051.55, 1053.05, 118908], [1704095100, 1053.05, 1056.5, 1050.6, 1055.7, 120947], [1704096000, 1055.7, 1056.6, 1053.0, 1055.0, 151557], [1704096900, 1055.0, 1057.95, 1054.6, 1056.25, 117675], [1704097800, 1056.25, 1057.15, 1055.5, 1055.95, 72441], [1704098700, 1055.85, 1056.3, 1051.6, 1052.2, 105995], [1704099600, 1052.2, 1055.2, 1052.2, 1054.05, 89074], [1704100500, 1054.05, 1055.5, 1053.3, 1054.75, 87254], [1704101400, 1054.75, 1056.0, 1045.2, 1045.5, 343990], [1704102300, 1045.5, 1047.95, 1039.6, 1041.1, 274238], [1704167100, 1047.85, 1048.5, 1039.2, 1043.5, 246863], [1704168000, 1043.5, 1051.0, 1039.5, 1049.8, 200892], [1704168900, 1049.8, 1049.8, 1039.05, 1040.05, 228692], [1704169800, 1040.4, 1046.1, 1036.4, 1043.1, 152082], [1704170700, 1043.1, 1043.75, 1035.8, 1037.85, 167086], [1704171600, 1037.85, 1041.05, 1031.1, 1035.7, 161082], [1704172500, 1035.4, 1040.95, 1034.7, 1040.9, 183754], [1704173400, 1040.9, 1046.6, 1039.4, 1043.0, 117087], [1704174300, 1043.0, 1056.8, 1042.25, 1054.1, 292283], [1704175200, 1054.1, 1056.15, 1050.35, 1055.2, 209885], [1704176100, 1055.4, 1057.8, 1053.05, 1054.45, 157758], [1704177000, 1054.15, 1070.0, 1051.5, 1067.5, 445979], [1704177900, 1067.5, 1068.75, 1060.05, 1060.4, 274150], [1704178800, 1060.4, 1062.95, 1060.0, 1060.2, 120430], [1704179700, 1060.2, 1061.35, 1057.05, 1057.15, 86207], [1704180600, 1057.15, 1058.95, 1054.6, 1055.55, 83615], [1704181500, 1055.55, 1058.75, 1054.7, 1056.8, 67941], [1704182400, 1056.8, 1059.6, 1056.55, 1058.0, 60792], [1704183300, 1058.0, 1061.5, 1056.5, 1060.85, 67750], [1704184200, 1060.75, 1065.25, 1060.45, 1062.9, 160352], [1704185100, 1062.95, 1069.2, 1061.0, 1065.7, 346816], [1704186000, 1065.95, 1076.6, 1065.0, 1075.45, 706225], [1704186900, 1075.45, 1082.9, 1074.0, 1077.05, 745933], [1704187800, 1077.05, 1081.4, 1073.7, 1077.3, 572111], [1704188700, 1077.1, 1080.5, 1076.7, 1078.55, 486685], [1704253500, 1105.0, 1116.45, 1091.7, 1105.75, 4356207], [1704254400, 1106.6, 1125.0, 1105.6, 1120.1, 2582510], [1704255300, 1120.0, 1140.85, 1119.55, 1136.6, 2772768], [1704256200, 1136.15, 1139.3, 1125.15, 1133.65, 1759018], [1704257100, 1134.1, 1134.6, 1111.0, 1125.0, 1817710], [1704258000, 1125.0, 1144.0, 1062.75, 1090.0, 5098103], [1704258900, 1089.55, 1117.0, 1076.4, 1099.25, 3139296], [1704259800, 1099.15, 1102.1, 1083.8, 1090.95, 1496378], [1704260700, 1090.95, 1098.5, 1086.6, 1086.7, 821683], [1704261600, 1086.75, 1088.0, 1078.55, 1084.0, 1009313], [1704262500, 1084.4, 1088.3, 1072.65, 1083.65, 794991], [1704263400, 1083.5, 1090.0, 1080.3, 1088.5, 621839], [1704264300, 1088.5, 1095.0, 1084.0, 1090.05, 548946], [1704265200, 1090.55, 1094.85, 1088.6, 1094.6, 362469], [1704266100, 1094.6, 1094.6, 1088.0, 1092.3, 254042], [1704267000, 1092.3, 1093.95, 1089.0, 1092.9, 281839], [1704267900, 1092.9, 1101.55, 1091.45, 1098.0, 674836], [1704268800, 1098.0, 1103.0, 1096.5, 1099.25, 466704], [1704269700, 1099.7, 1106.95, 1097.0, 1103.95, 528259], [1704270600, 1103.95, 1108.8, 1100.85, 1106.65, 531342], [1704271500, 1106.15, 1107.45, 1097.0, 1105.4, 649752], [1704272400, 1104.8, 1109.0, 1100.25, 1102.65, 514971], [1704273300, 1102.4, 1104.75, 1097.1, 1098.2, 398079], [1704274200, 1097.55, 1100.9, 1093.15, 1094.1, 739294], [1704275100, 1095.0, 1095.7, 1090.0, 1094.7, 834073], [1704339900, 1117.0, 1118.75, 1107.0, 1111.7, 2006855], [1704340800, 1111.6, 1112.65, 1103.55, 1109.25, 643015], [1704341700, 1109.25, 1114.6, 1108.05, 1112.0, 387867], [1704342600, 1112.0, 1117.95, 1111.45, 1117.0, 424811], [1704343500, 1117.0, 1118.3, 1112.05, 1113.95, 409929], [1704344400, 1113.55, 1114.7, 1109.4, 1113.75, 306039], [1704345300, 1113.95, 1114.0, 1108.55, 1110.0, 244404], [1704346200, 1110.0, 1113.6, 1109.65, 1112.05, 163253], [1704347100, 1112.05, 1114.95, 1110.0, 1111.65, 189317], [1704348000, 1112.0, 1116.0, 1111.05, 1114.55, 211444], [1704348900, 1114.3, 1114.8, 1111.05, 1114.6, 131186], [1704349800, 1114.6, 1117.0, 1113.35, 1115.95, 220591], [1704350700, 1115.95, 1122.05, 1115.0, 1119.4, 432818], [1704351600, 1119.4, 1121.4, 1118.0, 1119.5, 310336], [1704352500, 1119.5, 1122.0, 1115.9, 1116.5, 291205], [1704353400, 1116.5, 1119.7, 1116.45, 1116.7, 138659], [1704354300, 1116.65, 1117.95, 1115.0, 1116.6, 168877], [1704355200, 1116.6, 1118.7, 1116.05, 1118.65, 116462], [1704356100, 1118.5, 1121.7, 1117.9, 1121.5, 218069], [1704357000, 1121.5, 1131.0, 1121.35, 1125.9, 792961], [1704357900, 1125.9, 1127.5, 1121.3, 1123.8, 333105], [1704358800, 1123.95, 1127.95, 1123.5, 1126.65, 275721], [1704359700, 1126.65, 1127.0, 1124.2, 1125.55, 198052], [1704360600, 1125.1, 1125.95, 1122.05, 1123.6, 522028], [1704361500, 1123.3, 1124.5, 1120.55, 1122.0, 630709], [1704426300, 1129.1, 1141.0, 1125.4, 1137.25, 1129758], [1704427200, 1137.25, 1138.2, 1129.25, 1133.6, 888964], [1704428100, 1134.15, 1150.0, 1132.45, 1148.5, 869893], [1704429000, 1148.5, 1154.7, 1143.0, 1144.7, 789137], [1704429900, 1144.75, 1148.55, 1143.0, 1144.4, 265235], [1704430800, 1144.6, 1153.8, 1143.2, 1146.55, 421368], [1704431700, 1146.05, 1147.6, 1137.9, 1145.85, 543739], [1704432600, 1145.85, 1152.5, 1143.95, 1150.95, 363348], [1704433500, 1150.95, 1154.45, 1146.05, 1152.1, 322680], [1704434400, 1152.1, 1159.7, 1151.2, 1155.35, 648888], [1704435300, 1155.25, 1158.5, 1152.65, 1155.55, 261815], [1704436200, 1155.85, 1158.0, 1153.3, 1155.9, 173299], [1704437100, 1155.9, 1160.0, 1155.8, 1157.8, 234631], [1704438000, 1157.8, 1159.9, 1156.6, 1157.0, 182836], [1704438900, 1156.8, 1157.5, 1153.55, 1154.7, 185372], [1704439800, 1154.75, 1157.5, 1151.65, 1154.6, 171477], [1704440700, 1154.6, 1158.25, 1153.65, 1155.8, 171795], [1704441600, 1155.8, 1156.5, 1150.0, 1153.25, 224526], [1704442500, 1153.0, 1156.25, 1151.85, 1155.5, 187508], [1704443400, 1155.4, 1155.5, 1143.85, 1146.0, 409547], [1704444300, 1146.5, 1149.7, 1138.0, 1141.0, 566288], [1704445200, 1141.0, 1149.0, 1140.05, 1148.8, 357465], [1704446100, 1149.0, 1154.7, 1148.8, 1153.95, 335051], [1704447000, 1153.45, 1156.0, 1152.4, 1154.95, 410254], [1704447900, 1154.95, 1155.55, 1152.0, 1153.0, 503791], [1704685500, 1160.0, 1169.25, 1155.25, 1156.8, 1339377], [1704686400, 1157.2, 1162.6, 1153.0, 1159.6, 525511], [1704687300, 1159.6, 1162.0, 1152.0, 1159.3, 281377], [1704688200, 1159.3, 1166.0, 1157.1, 1164.25, 227338], [1704689100, 1164.35, 1172.0, 1161.0, 1167.65, 687230], [1704690000, 1168.35, 1169.5, 1162.5, 1163.7, 194934], [1704690900, 1163.7, 1167.45, 1163.65, 1166.85, 136937], [1704691800, 1167.3, 1171.7, 1166.0, 1168.55, 277605], [1704692700, 1168.7, 1176.9, 1168.1, 1174.5, 489154], [1704693600, 1174.65, 1180.0, 1174.45, 1179.85, 376087], [1704694500, 1179.75, 1181.9, 1173.5, 1174.15, 409912], [1704695400, 1174.3, 1182.0, 1173.95, 1179.95, 450075], [1704696300, 1179.95, 1179.95, 1172.4, 1172.5, 230884], [1704697200, 1172.55, 1174.0, 1171.0, 1171.5, 203943], [1704698100, 1171.5, 1176.6, 1169.8, 1175.75, 209904], [1704699000, 1175.7, 1179.7, 1175.1, 1178.7, 197441], [1704699900, 1178.7, 1181.0, 1177.3, 1179.9, 206377], [1704700800, 1179.65, 1181.0, 1177.35, 1178.35, 173274], [1704701700, 1178.55, 1178.8, 1175.3, 1177.9, 167215], [1704702600, 1178.1, 1178.5, 1173.65, 1175.5, 173803], [1704703500, 1175.5, 1176.1, 1170.75, 1170.75, 252998], [1704704400, 1170.7, 1172.3, 1166.3, 1170.0, 386909], [1704705300, 1169.75, 1174.2, 1168.05, 1168.8, 323409], [1704706200, 1169.05, 1170.65, 1166.05, 1166.3, 332327], [1704707100, 1166.7, 1174.95, 1165.0, 1172.4, 504236], [1704771900, 1182.0, 1198.5, 1178.5, 1194.6, 1279733], [1704772800, 1194.6, 1202.5, 1194.0, 1198.9, 1350116], [1704773700, 1199.0, 1213.25, 1198.4, 1209.0, 1722545], [1704774600, 1209.0, 1224.9, 1208.15, 1223.5, 1580779], [1704775500, 1223.75, 1228.0, 1220.7, 1224.9, 788796], [1704776400, 1224.9, 1229.9, 1223.4, 1225.5, 594595], [1704777300, 1225.9, 1226.0, 1214.05, 1215.2, 733522], [1704778200, 1214.5, 1216.0, 1205.5, 1206.0, 619900], [1704779100, 1206.45, 1208.95, 1201.5, 1202.2, 542980], [1704780000, 1202.2, 1207.0, 1198.5, 1204.0, 726599], [1704780900, 1204.0, 1207.0, 1199.4, 1201.5, 335128], [1704781800, 1201.75, 1201.9, 1191.55, 1195.45, 560108], [1704782700, 1195.1, 1195.95, 1190.1, 1195.25, 327840], [1704783600, 1195.2, 1199.25, 1191.25, 1192.15, 305523], [1704784500, 1192.0, 1194.7, 1190.1, 1194.0, 213212], [1704785400, 1194.0, 1194.0, 1190.35, 1192.5, 181907], [1704786300, 1192.8, 1197.5, 1192.4, 1197.1, 171034], [1704787200, 1197.0, 1202.5, 1195.1, 1201.0, 243244], [1704788100, 1201.0, 1205.55, 1200.55, 1204.55, 309530], [1704789000, 1204.85, 1207.35, 1203.4, 1205.2, 274604], [1704789900, 1205.7, 1206.45, 1192.8, 1194.55, 377728], [1704790800, 1194.55, 1202.1, 1193.65, 1195.8, 322798], [1704791700, 1195.8, 1201.55, 1195.8, 1199.75, 212845], [1704792600, 1199.8, 1200.9, 1194.0, 1195.35, 376562], [1704793500, 1195.55, 1202.0, 1192.2, 1200.95, 547639], [1704858300, 1220.0, 1220.0, 1198.75, 1200.4, 1446986], [1704859200, 1200.1, 1212.0, 1197.0, 1210.45, 660674], [1704860100, 1210.55, 1212.0, 1202.0, 1204.5, 482429], [1704861000, 1205.1, 1208.7, 1200.5, 1205.35, 357040], [1704861900, 1205.35, 1206.95, 1202.15, 1204.0, 201669], [1704862800, 1204.55, 1208.5, 1203.45, 1204.5, 153622], [1704863700, 1204.5, 1207.25, 1203.45, 1206.65, 102449], [1704864600, 1206.9, 1207.0, 1203.5, 1206.0, 120530], [1704865500, 1206.0, 1206.5, 1204.15, 1205.5, 101435], [1704866400, 1205.5, 1211.0, 1203.05, 1210.0, 221924], [1704867300, 1209.75, 1214.8, 1208.2, 1211.8, 407754], [1704868200, 1211.8, 1214.0, 1207.5, 1209.85, 286117], [1704869100, 1209.85, 1211.7, 1207.55, 1210.1, 145420], [1704870000, 1210.1, 1212.9, 1209.2, 1209.85, 180895], [1704870900, 1209.85, 1214.0, 1206.35, 1210.8, 320330], [1704871800, 1211.25, 1213.5, 1210.5, 1211.45, 139712], [1704872700, 1211.45, 1213.0, 1210.2, 1211.85, 88641], [1704873600, 1211.85, 1212.5, 1209.1, 1210.55, 141878], [1704874500, 1210.55, 1211.0, 1208.25, 1209.85, 132771], [1704875400, 1209.85, 1212.0, 1209.1, 1212.0, 84245], [1704876300, 1212.0, 1215.0, 1210.75, 1211.45, 235729], [1704877200, 1211.45, 1215.95, 1211.45, 1215.15, 213062], [1704878100, 1215.15, 1216.85, 1212.8, 1212.8, 201502], [1704879000, 1212.8, 1214.5, 1211.0, 1213.35, 245953], [1704879900, 1213.45, 1216.5, 1213.35, 1215.0, 363397], [1704944700, 1221.0, 1223.6, 1212.8, 1217.0, 719471], [1704945600, 1217.0, 1217.6, 1208.5, 1210.3, 385242], [1704946500, 1210.5, 1214.0, 1207.35, 1209.4, 245218], [1704947400, 1209.0, 1210.95, 1205.5, 1207.2, 189977], [1704948300, 1207.2, 1208.8, 1204.0, 1207.0, 165048], [1704949200, 1207.0, 1208.4, 1204.5, 1205.55, 103709], [1704950100, 1205.55, 1207.0, 1203.05, 1206.9, 110631], [1704951000, 1206.7, 1209.65, 1206.0, 1208.7, 79926], [1704951900, 1208.7, 1211.8, 1208.6, 1209.85, 99833], [1704952800, 1209.85, 1210.9, 1207.4, 1208.4, 58976], [1704953700, 1208.4, 1208.95, 1206.0, 1206.75, 55601], [1704954600, 1206.75, 1207.5, 1206.05, 1207.1, 41636], [1704955500, 1207.1, 1211.5, 1205.1, 1209.55, 113334], [1704956400, 1209.55, 1210.0, 1208.4, 1209.5, 57619], [1704957300, 1209.65, 1210.0, 1207.45, 1208.35, 49891], [1704958200, 1207.75, 1209.45, 1207.35, 1209.05, 43924], [1704959100, 1209.05, 1209.1, 1207.0, 1207.5, 46857], [1704960000, 1207.95, 1207.95, 1205.1, 1206.4, 82469], [1704960900, 1206.4, 1208.0, 1205.1, 1207.8, 71774], [1704961800, 1207.8, 1207.95, 1201.1, 1202.25, 159484], [1704962700, 1202.25, 1206.0, 1201.05, 1205.45, 123707], [1704963600, 1205.45, 1206.7, 1204.8, 1205.7, 92182], [1704964500, 1205.7, 1206.45, 1204.65, 1205.0, 66788], [1704965400, 1205.1, 1205.4, 1202.45, 1202.8, 181478], [1704966300, 1202.8, 1205.25, 1200.0, 1204.0, 375611], [1705031100, 1210.4, 1210.4, 1201.1, 1203.0, 416317], [1705032000, 1203.0, 1216.0, 1201.05, 1213.1, 362542], [1705032900, 1213.05, 1218.75, 1212.3, 1216.95, 334357], [1705033800, 1217.0, 1218.05, 1214.55, 1216.45, 188279], [1705034700, 1216.45, 1218.55, 1215.25, 1216.25, 113501], [1705035600, 1216.25, 1216.75, 1213.0, 1214.05, 86451], [1705036500, 1214.05, 1214.5, 1212.25, 1212.8, 52536], [1705037400, 1212.8, 1213.4, 1207.8, 1209.55, 146665], [1705038300, 1209.5, 1209.65, 1207.0, 1209.0, 73147], [1705039200, 1209.0, 1209.95, 1207.6, 1207.95, 88058], [1705040100, 1207.95, 1209.7, 1206.65, 1206.8, 104383], [1705041000, 1206.65, 1209.5, 1204.35, 1209.3, 121243], [1705041900, 1209.3, 1209.6, 1206.5, 1208.55, 63213], [1705042800, 1208.55, 1210.5, 1205.55, 1206.35, 105133], [1705043700, 1206.35, 1207.5, 1205.55, 1207.3, 64563], [1705044600, 1207.05, 1210.5, 1206.65, 1209.9, 84056], [1705045500, 1209.9, 1209.9, 1207.3, 1209.1, 118794], [1705046400, 1209.2, 1214.9, 1208.55, 1210.1, 211324], [1705047300, 1210.1, 1211.3, 1207.85, 1210.4, 129487], [1705048200, 1210.45, 1210.7, 1206.5, 1207.9, 137899], [1705049100, 1207.9, 1210.55, 1206.8, 1209.9, 170222], [1705050000, 1209.9, 1213.35, 1209.65, 1211.45, 215834], [1705050900, 1211.4, 1211.45, 1207.6, 1207.9, 131840], [1705051800, 1207.9, 1209.2, 1205.25, 1206.5, 158914], [1705052700, 1206.25, 1208.95, 1205.8, 1207.0, 231582], [1705290300, 1214.0, 1215.35, 1207.1, 1207.7, 306662], [1705291200, 1207.4, 1207.65, 1203.15, 1203.65, 201968], [1705292100, 1203.65, 1203.65, 1191.0, 1191.45, 221137], [1705293000, 1191.45, 1196.6, 1189.1, 1192.1, 196022], [1705293900, 1192.1, 1195.5, 1192.0, 1195.1, 77414], [1705294800, 1195.15, 1197.8, 1194.55, 1195.8, 83073], [1705295700, 1195.8, 1197.4, 1193.1, 1197.4, 78127], [1705296600, 1197.5, 1207.8, 1197.1, 1207.05, 230837], [1705297500, 1207.05, 1209.7, 1205.55, 1207.8, 172422], [1705298400, 1207.8, 1209.8, 1205.0, 1208.25, 95691], [1705299300, 1208.25, 1208.4, 1205.5, 1205.5, 43375], [1705300200, 1205.5, 1207.55, 1204.6, 1205.4, 50050], [1705301100, 1205.4, 1206.8, 1204.7, 1204.8, 56925], [1705302000, 1204.8, 1206.6, 1204.75, 1206.0, 44468], [1705302900, 1205.85, 1206.45, 1204.1, 1204.15, 35633], [1705303800, 1204.15, 1204.4, 1202.0, 1203.0, 89613], [1705304700, 1203.05, 1204.25, 1201.15, 1202.0, 49289], [1705305600, 1202.0, 1203.0, 1201.1, 1202.95, 48303], [1705306500, 1202.95, 1208.1, 1200.5, 1208.1, 94434], [1705307400, 1208.1, 1209.9, 1204.2, 1205.5, 111509], [1705308300, 1205.5, 1207.4, 1204.0, 1204.75, 61391], [1705309200, 1204.75, 1207.2, 1204.0, 1207.0, 59523], [1705310100, 1207.0, 1207.5, 1205.2, 1205.65, 68552], [1705311000, 1205.65, 1206.9, 1202.0, 1202.75, 121568], [1705311900, 1202.3, 1207.5, 1202.0, 1203.6, 226581], [1705376700, 1203.6, 1212.0, 1202.05, 1205.15, 390391], [1705377600, 1205.15, 1206.95, 1204.05, 1205.45, 151489], [1705378500, 1205.45, 1207.85, 1202.65, 1203.5, 106153], [1705379400, 1203.45, 1203.45, 1199.0, 1199.9, 223007], [1705380300, 1200.0, 1200.55, 1197.75, 1200.55, 173847], [1705381200, 1200.05, 1200.85, 1199.4, 1199.85, 69415], [1705382100, 1199.85, 1200.05, 1197.6, 1199.6, 97619], [1705383000, 1199.7, 1200.1, 1199.0, 1199.65, 42458], [1705383900, 1199.6, 1200.2, 1199.0, 1199.25, 88253], [1705384800, 1199.25, 1199.55, 1196.0, 1197.2, 107163], [1705385700, 1197.2, 1200.95, 1194.65, 1200.0, 145695], [1705386600, 1200.0, 1200.35, 1196.5, 1197.7, 82503], [1705387500, 1197.65, 1200.4, 1197.0, 1198.6, 66203], [1705388400, 1198.6, 1200.0, 1198.6, 1199.7, 48517], [1705389300, 1199.7, 1200.1, 1198.0, 1199.2, 54207], [1705390200, 1199.1, 1199.35, 1191.4, 1193.7, 184605], [1705391100, 1193.7, 1196.2, 1190.0, 1193.3, 166164], [1705392000, 1193.0, 1193.1, 1186.8, 1191.15, 184828], [1705392900, 1191.0, 1193.45, 1190.0, 1191.9, 77747], [1705393800, 1191.75, 1193.95, 1190.15, 1192.85, 86750], [1705394700, 1192.8, 1194.2, 1191.55, 1193.75, 101732], [1705395600, 1193.7, 1195.85, 1191.65, 1195.15, 98757], [1705396500, 1195.1, 1195.5, 1193.05, 1194.45, 85896], [1705397400, 1194.3, 1195.4, 1193.1, 1193.65, 130566], [1705398300, 1193.65, 1195.0, 1190.4, 1194.5, 209428], [1705463100, 1180.0, 1204.7, 1177.45, 1190.5, 747626], [1705464000, 1190.0, 1193.15, 1189.0, 1189.4, 227245], [1705464900, 1189.6, 1191.55, 1187.0, 1189.1, 175718], [1705465800, 1189.3, 1191.5, 1188.1, 1191.2, 55863], [1705466700, 1190.55, 1196.9, 1190.55, 1196.4, 144476], [1705467600, 1196.35, 1200.8, 1189.05, 1191.5, 171918], [1705468500, 1191.5, 1193.95, 1190.6, 1192.8, 61654], [1705469400, 1192.45, 1193.5, 1184.4, 1187.25, 549028], [1705470300, 1187.25, 1187.3, 1181.25, 1182.4, 270949], [1705471200, 1182.4, 1183.15, 1176.25, 1178.3, 342681], [1705472100, 1178.6, 1178.95, 1175.75, 1177.8, 98952], [1705473000, 1177.75, 1178.45, 1173.1, 1177.15, 174164], [1705473900, 1177.15, 1179.85, 1176.2, 1177.9, 100437], [1705474800, 1177.8, 1180.5, 1177.5, 1178.1, 89895], [1705475700, 1178.1, 1179.7, 1177.0, 1178.15, 69270], [1705476600, 1178.15, 1179.25, 1175.8, 1177.5, 85564], [1705477500, 1177.5, 1179.0, 1175.05, 1175.4, 68818], [1705478400, 1175.4, 1176.8, 1172.0, 1175.45, 85978], [1705479300, 1175.45, 1181.45, 1169.3, 1176.05, 120547], [1705480200, 1176.05, 1179.0, 1175.25, 1175.25, 121773], [1705481100, 1175.25, 1176.8, 1165.65, 1166.35, 128201], [1705482000, 1165.65, 1168.55, 1160.5, 1161.75, 347211], [1705482900, 1161.8, 1163.0, 1159.45, 1161.8, 385968], [1705483800, 1161.45, 1168.95, 1161.1, 1167.05, 291786], [1705484700, 1167.05, 1174.1, 1165.6, 1169.9, 352302], [1705549500, 1171.05, 1184.3, 1170.3, 1179.65, 653526], [1705550400, 1179.65, 1182.35, 1159.5, 1164.55, 732760], [1705551300, 1164.9, 1165.2, 1143.45, 1152.45, 1239312], [1705552200, 1152.45, 1165.75, 1151.35, 1164.5, 604930], [1705553100, 1164.5, 1165.95, 1155.5, 1156.25, 296575], [1705554000, 1156.25, 1158.75, 1151.9, 1155.0, 264935], [1705554900, 1155.0, 1158.65, 1153.65, 1155.75, 305551], [1705555800, 1155.75, 1156.0, 1150.6, 1154.75, 129201], [1705556700, 1155.0, 1155.5, 1152.65, 1154.95, 65537], [1705557600, 1154.95, 1157.05, 1149.0, 1152.05, 197098], [1705558500, 1152.05, 1157.35, 1151.4, 1156.5, 47191], [1705559400, 1156.5, 1157.5, 1152.1, 1154.55, 121478], [1705560300, 1154.55, 1156.95, 1153.05, 1153.55, 51011], [1705561200, 1153.55, 1155.75, 1144.1, 1144.75, 115634], [1705562100, 1144.75, 1149.45, 1144.3, 1148.25, 64531], [1705563000, 1148.3, 1150.85, 1147.5, 1149.2, 76033], [1705563900, 1149.2, 1152.3, 1148.8, 1151.55, 55621], [1705564800, 1151.55, 1152.0, 1148.65, 1150.3, 37626], [1705565700, 1150.4, 1153.4, 1149.5, 1152.45, 44827], [1705566600, 1152.95, 1155.5, 1151.5, 1154.5, 38149], [1705567500, 1154.5, 1155.15, 1151.8, 1153.0, 39592], [1705568400, 1153.25, 1155.85, 1151.6, 1155.35, 61964], [1705569300, 1155.5, 1157.1, 1153.0, 1155.1, 145206], [1705570200, 1155.0, 1156.0, 1153.2, 1154.2, 157779], [1705571100, 1154.25, 1159.2, 1152.2, 1155.0, 372151], [1705635900, 1162.25, 1166.8, 1159.6, 1163.55, 326496], [1705636800, 1163.15, 1164.3, 1155.5, 1156.5, 190734], [1705637700, 1156.6, 1160.45, 1155.0, 1159.4, 153605], [1705638600, 1159.45, 1159.55, 1154.2, 1157.55, 126747], [1705639500, 1157.55, 1162.45, 1157.55, 1160.85, 135292], [1705640400, 1160.85, 1162.2, 1158.6, 1161.15, 97171], [1705641300, 1161.15, 1161.7, 1158.75, 1158.95, 65611], [1705642200, 1158.95, 1160.0, 1155.0, 1156.8, 81864], [1705643100, 1156.8, 1156.8, 1153.0, 1154.9, 73908], [1705644000, 1154.9, 1155.6, 1151.0, 1153.5, 104915], [1705644900, 1153.5, 1157.8, 1153.0, 1155.55, 77447], [1705645800, 1155.55, 1157.5, 11

         open     high      low    close  volume                  datetime
0     1026.55  1028.90  1025.00  1026.15  156982 2024-01-01 09:30:00+05:30
1     1026.00  1027.05  1024.10  1024.50   59143 2024-01-01 09:45:00+05:30
2     1024.60  1026.35  1023.00  1025.00   57906 2024-01-01 10:00:00+05:30
3     1025.00  1025.25  1023.10  1023.60   31236 2024-01-01 10:15:00+05:30
4     1023.60  1025.80  1023.10  1025.00   34453 2024-01-01 10:30:00+05:30
...       ...      ...      ...      ...     ...                       ...
1727  1351.55  1355.35  1351.25  1353.75  113633 2024-04-10 14:30:00+05:30
1728  1354.00  1355.25  1352.50  1353.15  166782 2024-04-10 14:45:00+05:30
1729  1353.15  1353.80  1350.00  1352.50  496089 2024-04-10 15:00:00+05:30
1730  1352.45  1354.80  1351.70  1352.50  236980 2024-04-10 15:15:00+05:30
1731  1352.50  1354.90  1350.15  1352.00  545775 2024-04-10 15:30:00+05:30

[1732 rows x 6 columns]

In [11]:
def combined_data_function(ticker=ticker, resolution=resolution, start_date=start_date_formatted, end_date=end_date):
    fyers = fyersModel.FyersModel(client_id=client_id, is_async=False, token=access_token, log_path="")

    data = {
        "symbol": ticker,  #"NSE:SBIN-EQ",
        "resolution": resolution,  #"15",
        "date_format": "1",
        "range_from": start_date,  #"2018-01-01",
        "range_to": end_date,  #"2018-03-31",
        "cont_flag": "1",
        "oi_flag": 1
    }

    response = fyers.history(data=data)
    df = fyers_history_to_df(response)
    df = df.set_index("datetime")

    return df

In [27]:
# ticker = "NSE:RELIANCE-EQ"
# df = combined_data_function("NSE:RELIANCE-EQ", resolution=5, start_date="2025-10-01", end_date="2025-12-31")
# df.head()

In [28]:
# file_name= ticker.split(":")[1].split("-")[0]
# df.to_csv(f"./5_minutes_data/{file_name}.csv", index=None)

#### Fetch Multiple Years for any minutes interval

In [12]:
# Generate 3-month intervals
date_ranges = []
current_start = start_date

while current_start < end_date:
    # Calculate end of 3-month period
    current_end = current_start + timedelta(days=90)

    # Don't exceed the final end date
    if current_end > end_date:
        current_end = end_date

    date_ranges.append({
        'start': current_start.strftime('%Y-%m-%d'),
        'end': current_end.strftime('%Y-%m-%d')
    })

    # Move to next period (start from day after current end)
    current_start = current_end + timedelta(days=1)

print(f"Total periods to fetch: {len(date_ranges)}")

# Fetch and append data
all_data = []

for i, period in enumerate(date_ranges):
    print(f"Fetching period {i + 1}/{len(date_ranges)}: {period['start']} to {period['end']}")

    try:
        df = combined_data_function(
            ticker=ticker,
            resolution=resolution,
            start_date=period['start'],
            end_date=period['end']
        )

        all_data.append(df)
        print(f"  ✓ Fetched {len(df)} rows")

        # Add delay to avoid rate limiting
        time.sleep(1)

    except Exception as e:
        print(f"  ✗ Error fetching data: {e}")
        continue

# Combine all dataframes
if all_data:
    combined_df = pd.concat(all_data, ignore_index=False)
    combined_df = combined_df.sort_index()

    # Remove any duplicate timestamps
    combined_df = combined_df[~combined_df.index.duplicated(keep='first')]

    print(f"\nTotal rows collected: {len(combined_df)}")
    print(f"Date range: {combined_df.index.min()} to {combined_df.index.max()}")

    # Save to CSV
    file_name = ticker.split(":")[1].split("-")[0]
    # combined_df.to_csv(output_path)

    # print(f"✓ Saved to {output_path}")
else:
    print("No data collected")

Total periods to fetch: 10
Fetching period 1/10: 2024-01-01 to 2024-03-31

In [13]:
# output_path = f"./5_min_data/{file_name}.csv"
output_path = f"./{resolution}_min_data/{file_name}.csv"
output_path = f"./1_hour_data/{file_name}.csv"

combined_df.to_csv(output_path)

##### Close

In [31]:
# len(ticker_list)

In [ ]:
#### Fetch FYERS historical data in 3-month chunks, concatenate, and save as CSV.

In [14]:
import pandas as pd
from datetime import datetime
from dateutil.relativedelta import relativedelta
import os


def fetch_and_save_fyers_data(
        ticker=ticker,
        resolution=resolution,
        start_date=start_date,
        end_date=end_date,
        save_dir="./Data/15_min_data"
):
    """
    Fetch FYERS historical data in 3-month chunks, concatenate, and save as CSV.
    """

    # Initialize FYERS
    fyers = fyersModel.FyersModel(
        client_id=client_id,
        is_async=False,
        token=access_token,
        log_path=""
    )
    start_dt = datetime.strptime(start_date_formatted, "%Y-%m-%d")
    end_dt = datetime.strptime(end_date_formatted, "%Y-%m-%d")
    dfs = []
    curr_start = start_dt

    while curr_start <= end_date:
        # curr_end = min(curr_start + relativedelta(months=3) - relativedelta(days=1), end_dt)
        curr_end = curr_start + relativedelta(days=100)
        data = {
            "symbol": ticker,
            "resolution": str(resolution),
            "date_format": "1",
            "range_from": curr_start.strftime("%Y-%m-%d"),
            "range_to": curr_end.strftime("%Y-%m-%d"),
            "cont_flag": "1"
        }

        print(f"Fetching: {data['range_from']} → {data['range_to']}")

        response = fyers.history(data=data)
        print("Response:", response)
        if response.get("candles"):
            df = fyers_history_to_df(response)
            df["datetime"] = pd.to_datetime(df["datetime"])
            dfs.append(df)
        else:
            print(f"No data returned for {data['range_from']} → {data['range_to']}")

        curr_start = curr_end + relativedelta(days=1)

    if not dfs:
        raise ValueError("No data fetched for the given date range.")

    # Concatenate once (important for performance)
    final_df = (
        pd.concat(dfs, ignore_index=True)
        .drop_duplicates(subset=["datetime"])
        .sort_values("datetime")
        .set_index("datetime")
    )

    # Prepare filename
    os.makedirs(save_dir, exist_ok=True)
    symbol_name = ticker.replace(":", "_").replace("-", "_").lower()
    filepath = os.path.join(save_dir, f"{symbol_name}.csv")

    final_df.to_csv(filepath)
    print(f"Saved data → {filepath}")

    return final_df


print(ticker, resolution, start_date, end_date)
fetch_and_save_fyers_data(
    ticker=ticker,
    resolution=resolution,
    start_date=start_date,
    end_date=end_date,
    save_dir="15_min_data"
)

NSE:ADANIPORTS-EQ 15 2024-01-01 00:00:00 2026-04-25 18:10:26.873675
Fetching: 2024-01-01 → 2024-04-10

                              open     high     low    close  volume
datetime
2024-01-01 09:30:00+05:30  1026.55  1028.90  1025.0  1026.15  156982
2024-01-01 09:45:00+05:30  1026.00  1027.05  1024.1  1024.50   59143
2024-01-01 10:00:00+05:30  1024.60  1026.35  1023.0  1025.00   57906
2024-01-01 10:15:00+05:30  1025.00  1025.25  1023.1  1023.60   31236
2024-01-01 10:30:00+05:30  1023.60  1025.80  1023.1  1025.00   34453
...                            ...      ...     ...      ...     ...
2026-04-24 14:30:00+05:30  1568.50  1577.20  1567.4  1575.30  104282
2026-04-24 14:45:00+05:30  1575.60  1586.40  1575.6  1583.70  172894
2026-04-24 15:00:00+05:30  1583.70  1586.20  1579.1  1580.20  101111
2026-04-24 15:15:00+05:30  1580.10  1587.30  1576.8  1583.30  128177
2026-04-24 15:30:00+05:30  1584.50  1591.70  1583.6  1590.00  185832

[14273 rows x 5 columns]

In [15]:
ticker_list = ["NSE:ADANIPORTS-EQ", "NSE:SBIN-EQ", "NSE:RELIANCE-EQ"]
for ticker in ticker_list:
    fetch_and_save_fyers_data(
        ticker=ticker,
        resolution=resolution,
        start_date=start_date,
        end_date=end_date,
        save_dir="15_min_data"
    )

Fetching: 2024-01-01 → 2024-04-10

In [34]:
# def fetch_and_save_fyers_data_worker(args):
#     return fetch_and_save_fyers_data(**args)

#### Batch Processing

In [35]:
# from concurrent.futures import ThreadPoolExecutor, as_completed
# import time
# from pathlib import Path
# import json
# from datetime import datetime

# def parallel_fetch_fyers(
#     ticker_list,
#     resolution=15,
#     start_date="2018-01-01",
#     end_date="2026-01-04",
#     save_dir="./Data/15_min_data",
#     max_workers=3,
#     rate_limit_delay=0.5
# ):
#     """
#     Parallel historical fetch with rate limiting and progress tracking.
#     """

#     tasks = [
#         {
#             "ticker": ticker,
#             "resolution": resolution,
#             "start_date": start_date,
#             "end_date": end_date,
#             "save_dir": save_dir
#         }
#         for ticker in ticker_list
#     ]

#     results = {"success": [], "failed": [], "errors": {}}

#     with ThreadPoolExecutor(max_workers=max_workers) as executor:
#         # Submit with slight delays to avoid rate limit spikes
#         futures = {}
#         for i, task in enumerate(tasks):
#             future = executor.submit(fetch_and_save_fyers_data_worker, task)
#             futures[future] = task["ticker"]
#             if i < len(tasks) - 1:
#                 time.sleep(rate_limit_delay)

#         # Track progress
#         start_time = time.time()
#         for i, future in enumerate(as_completed(futures), 1):
#             ticker = futures[future]
#             elapsed = time.time() - start_time
#             avg_time = elapsed / i
#             eta = avg_time * (len(tasks) - i)

#             try:
#                 future.result()
#                 results["success"].append(ticker)
#                 print(f"✅ [{i}/{len(tasks)}] {ticker} | ETA: {eta/60:.1f}m")
#             except Exception as e:
#                 error_msg = str(e)[:200]
#                 results["failed"].append(ticker)
#                 results["errors"][ticker] = error_msg
#                 print(f"❌ [{i}/{len(tasks)}] {ticker} | Error: {error_msg}")

#     return results


# def batch_fetch_fyers(
#     ticker_list,
#     batch_size=20,
#     max_retries=2,
#     resolution=15,
#     start_date="2018-01-01",
#     end_date="2026-01-04",
#     save_dir="./Data/15_min_data",
#     max_workers=3,
#     rate_limit_delay=0.5,
#     save_progress=True
# ):
#     """
#     Fetch 100+ tickers in batches with retry logic and progress saving.
#     """

#     print(f"🚀 Starting batch fetch for {len(ticker_list)} tickers")
#     print(f"   Batch size: {batch_size}, Workers: {max_workers}")
#     print(f"   Rate limit delay: {rate_limit_delay}s")
#     print("="*60)

#     all_results = {
#         "success": [],
#         "failed": [],
#         "errors": {},
#         "metadata": {
#             "total_tickers": len(ticker_list),
#             "start_time": datetime.now().isoformat(),
#             "resolution": resolution,
#             "date_range": f"{start_date} to {end_date}"
#         }
#     }

#     # Process in batches
#     num_batches = (len(ticker_list) + batch_size - 1) // batch_size

#     for batch_num in range(num_batches):
#         start_idx = batch_num * batch_size
#         end_idx = min(start_idx + batch_size, len(ticker_list))
#         batch = ticker_list[start_idx:end_idx]

#         print(f"\n📦 BATCH {batch_num + 1}/{num_batches}")
#         print(f"   Tickers {start_idx + 1}-{end_idx} of {len(ticker_list)}")
#         print(f"   Tickers: {', '.join(batch[:5])}{'...' if len(batch) > 5 else ''}")
#         print("-"*60)

#         # Fetch this batch
#         batch_results = parallel_fetch_fyers(
#             ticker_list=batch,
#             resolution=resolution,
#             start_date=start_date,
#             end_date=end_date,
#             save_dir=save_dir,
#             max_workers=max_workers,
#             rate_limit_delay=rate_limit_delay
#         )

#         # Aggregate results
#         all_results["success"].extend(batch_results["success"])
#         all_results["failed"].extend(batch_results["failed"])
#         all_results["errors"].update(batch_results["errors"])

#         # Save progress checkpoint
#         if save_progress:
#             progress_file = Path(save_dir) / "fetch_progress.json"
#             with open(progress_file, 'w') as f:
#                 json.dump(all_results, f, indent=2)

#         # Cooldown between batches (except last batch)
#         if batch_num < num_batches - 1:
#             cooldown = 3
#             print(f"\n💤 Cooldown {cooldown}s before next batch...")
#             time.sleep(cooldown)

#     # Retry failed tickers
#     if all_results["failed"] and max_retries > 0:
#         print(f"\n{'='*60}")
#         print(f"🔄 RETRY PHASE: {len(all_results['failed'])} failed tickers")
#         print(f"   Retries remaining: {max_retries}")
#         print("="*60)

#         for retry_num in range(max_retries):
#             if not all_results["failed"]:
#                 break

#             failed_tickers = all_results["failed"].copy()
#             all_results["failed"] = []

#             print(f"\n🔄 Retry {retry_num + 1}/{max_retries}")

#             retry_results = parallel_fetch_fyers(
#                 ticker_list=failed_tickers,
#                 resolution=resolution,
#                 start_date=start_date,
#                 end_date=end_date,
#                 save_dir=save_dir,
#                 max_workers=max(1, max_workers - 1),  # More conservative
#                 rate_limit_delay=rate_limit_delay * 1.5
#             )

#             all_results["success"].extend(retry_results["success"])
#             all_results["failed"] = retry_results["failed"]
#             all_results["errors"].update(retry_results["errors"])

#             if retry_num < max_retries - 1 and all_results["failed"]:
#                 time.sleep(5)  # Longer cooldown between retries

#     # Final summary
#     all_results["metadata"]["end_time"] = datetime.now().isoformat()
#     print_final_summary(all_results, save_dir)

#     # Save final results
#     if save_progress:
#         final_file = Path(save_dir) / f"fetch_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
#         with open(final_file, 'w') as f:
#             json.dump(all_results, f, indent=2)
#         print(f"\n💾 Results saved to: {final_file}")

#     return all_results


# def print_final_summary(results, save_dir):
#     """Print comprehensive summary of fetch operation."""
#     total = results["metadata"]["total_tickers"]
#     success_count = len(results["success"])
#     failed_count = len(results["failed"])
#     success_rate = (success_count / total * 100) if total > 0 else 0

#     print(f"\n{'='*60}")
#     print("📊 FINAL SUMMARY")
#     print("="*60)
#     print(f"✅ Success: {success_count}/{total} ({success_rate:.1f}%)")
#     print(f"❌ Failed:  {failed_count}/{total}")

#     if results["failed"]:
#         print(f"\n⚠️  Failed tickers ({len(results['failed'])}):")
#         for ticker in results["failed"][:10]:
#             error = results["errors"].get(ticker, "Unknown error")
#             print(f"   • {ticker}: {error[:80]}")
#         if len(results["failed"]) > 10:
#             print(f"   ... and {len(results['failed']) - 10} more")

#     # Check what files were actually created
#     saved_files = list(Path(save_dir).glob("*.csv"))
#     print(f"\n💾 Files saved: {len(saved_files)} CSV files in {save_dir}")

#     print("="*60)


# def resume_failed_fetch(results_file, **kwargs):
#     """Resume fetch from saved progress file."""
#     with open(results_file, 'r') as f:
#         previous_results = json.load(f)

#     failed_tickers = previous_results.get("failed", [])

#     if not failed_tickers:
#         print("✅ No failed tickers to resume!")
#         return previous_results

#     print(f"🔄 Resuming {len(failed_tickers)} failed tickers from {results_file}")

#     return batch_fetch_fyers(
#         ticker_list=failed_tickers,
#         **kwargs
#     )

In [36]:

# # Run with optimal settings for BSE/NSE
# results = batch_fetch_fyers(
#     ticker_list=ticker_list,
#     batch_size=20,           # Process 20 tickers per batch
#     max_retries=2,           # Retry failed tickers twice
#     resolution=15,
#     start_date="2018-01-01",
#     end_date="2026-01-04",
#     save_dir="./Data/15_min_data",
#     max_workers=3,           # 3 concurrent requests
#     rate_limit_delay=0.5,    # 0.5s between request submissions
#     save_progress=True       # Save checkpoint after each batch
# )